import { describe, it, expect } from 'vitest';
import { mkdtempSync, rmSync, readFileSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SmartInit } from '../../src/init/index.js';
import { DnaStorage } from '../../src/dna/storage.js';
import { IntentStore } from '../../src/brain/intent.js';
import type { ScanResult } from '../../src/core/scanner.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_DIR = resolve(__dirname, '../fixtures/init-project');

function makeTmpDirs(): { symbioteHome: string; brainDir: string; cleanup: () => void } {
    const symbioteHome = mkdtempSync(join(tmpdir(), 'symbiote-int-home-'));
    const brainDir = mkdtempSync(join(tmpdir(), 'symbiote-int-brain-'));
    return {
        symbioteHome,
        brainDir,
        cleanup: () => {
            rmSync(symbioteHome, { recursive: true, force: true });
            rmSync(brainDir, { recursive: true, force: true });
        },
    };
}

const scanResult: ScanResult = {
    filesScanned: 25,
    filesSkipped: 5,
    nodesCreated: 80,
    edgesCreated: 60,
    errors: [],
};

describe('SmartInit integration', () => {
    it('produces complete overview with all sections', () => {
        const { symbioteHome, brainDir, cleanup } = makeTmpDirs();
        try {
            const init = new SmartInit({
                projectRoot: FIXTURE_DIR,
                symbioteHome,
                brainDir,
                scanResult,
            });
            init.run();

            const overview = readFileSync(join(brainDir, 'intent', 'overview.md'), 'utf-8');

            expect(overview).toContain('# init-project');
            expect(overview).toContain('A Next.js app with Drizzle ORM');
            expect(overview).toContain('## Tech Stack');
            expect(overview).toContain('## Architecture');
            expect(overview).toContain('## Entry Points');
            expect(overview).toContain('## Graph Stats');
            expect(overview).toContain('Files scanned: 25');
            expect(overview).toContain('Auto-generated by Symbiote');
        } finally {
            cleanup();
        }
    });

    it('creates intent entries from CLAUDE.md', () => {
        const { symbioteHome, brainDir, cleanup } = makeTmpDirs();
        try {
            const init = new SmartInit({
                projectRoot: FIXTURE_DIR,
                symbioteHome,
                brainDir,
                scanResult,
            });
            const result = init.run();

            expect(result.intentEntriesCreated).toBeGreaterThan(0);

            const store = new IntentStore(brainDir);
            const constraints = store.listEntries('constraint');
            const decisions = store.listEntries('decision');
            const total = constraints.length + decisions.length;

            expect(total).toBe(result.intentEntriesCreated);
        } finally {
            cleanup();
        }
    });

    it('creates DNA entries', () => {
        const { symbioteHome, brainDir, cleanup } = makeTmpDirs();
        try {
            const init = new SmartInit({
                projectRoot: FIXTURE_DIR,
                symbioteHome,
                brainDir,
                scanResult,
            });
            const result = init.run();

            expect(result.dnaEntriesImported).toBeGreaterThan(0);

            const dnaDir = join(symbioteHome, 'dna');
            const storage = new DnaStorage(dnaDir);
            const entries = storage.listEntries();

            expect(entries.length).toBe(result.dnaEntriesImported);
        } finally {
            cleanup();
        }
    });

    it('is idempotent — running twice does not duplicate entries', () => {
        const { symbioteHome, brainDir, cleanup } = makeTmpDirs();
        try {
            const options = {
                projectRoot: FIXTURE_DIR,
                symbioteHome,
                brainDir,
                scanResult,
            };

            const first = new SmartInit(options).run();
            const second = new SmartInit(options).run();

            expect(second.dnaEntriesImported).toBe(0);
            expect(second.intentEntriesCreated).toBe(0);
            expect(second.dnaEntriesLoaded).toBe(first.dnaEntriesImported);

            const dnaDir = join(symbioteHome, 'dna');
            const storage = new DnaStorage(dnaDir);
            const entries = storage.listEntries();
            expect(entries.length).toBe(first.dnaEntriesImported);
        } finally {
            cleanup();
        }
    });

    it('detects all expected tech stack entries', () => {
        const { symbioteHome, brainDir, cleanup } = makeTmpDirs();
        try {
            const init = new SmartInit({
                projectRoot: FIXTURE_DIR,
                symbioteHome,
                brainDir,
                scanResult,
            });
            const result = init.run();

            const names = result.techStack.map((t) => t.name);
            expect(names).toContain('Next.js');
            expect(names).toContain('React');
            expect(names).toContain('Drizzle');
            expect(names).toContain('Tailwind');
            expect(names).toContain('TypeScript');
        } finally {
            cleanup();
        }
    });
});
