import { describe, it, expect } from 'vitest';
import { generateSmartOverview } from '../../src/init/overview-generator.js';
import type { ProjectAnalysis, ClassifiedRule } from '../../src/init/parsers/types.js';
import type { ScanResult } from '../../src/core/scanner.js';

function makeScanResult(overrides?: Partial<ScanResult>): ScanResult {
    return {
        filesScanned: 42,
        filesSkipped: 3,
        nodesCreated: 120,
        edgesCreated: 85,
        errors: [],
        ...overrides,
    };
}

function makeAnalysis(overrides?: Partial<ProjectAnalysis>): ProjectAnalysis {
    return {
        techStack: [
            { name: 'React', version: '19.0.0', category: 'framework' },
            { name: 'Vitest', version: '3.0.0', category: 'testing' },
            { name: 'Tailwind', version: '4.0.0', category: 'styling' },
        ],
        architecture: [
            { pattern: 'src-directory', confidence: 0.8 },
            { pattern: 'component-library', confidence: 0.7 },
        ],
        conventions: [],
        entryPoints: ['src/index.ts'],
        description: 'A great project',
        ...overrides,
    };
}

describe('generateSmartOverview', () => {
    it('includes project name as title', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('# my-app');
    });

    it('includes description when present', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('A great project');
    });

    it('handles missing description', () => {
        const analysis = makeAnalysis({ description: undefined });
        const output = generateSmartOverview('my-app', analysis, makeScanResult());
        expect(output).toContain('# my-app');
        expect(output).not.toContain('undefined');
    });

    it('includes tech stack grouped by category', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('## Tech Stack');
        expect(output).toContain('**Framework**');
        expect(output).toContain('- React (19.0.0)');
        expect(output).toContain('**Testing**');
        expect(output).toContain('- Vitest (3.0.0)');
    });

    it('handles empty tech stack', () => {
        const analysis = makeAnalysis({ techStack: [] });
        const output = generateSmartOverview('my-app', analysis, makeScanResult());
        expect(output).not.toContain('## Tech Stack');
    });

    it('includes architecture signals sorted by confidence', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('## Architecture');
        expect(output).toContain('src-directory (80%)');
        const srcIdx = output.indexOf('src-directory');
        const compIdx = output.indexOf('component-library');
        expect(srcIdx).toBeLessThan(compIdx);
    });

    it('includes entry points', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('## Entry Points');
        expect(output).toContain('`src/index.ts`');
    });

    it('includes scan stats', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('## Graph Stats');
        expect(output).toContain('Files scanned: 42');
        expect(output).toContain('Nodes: 120');
        expect(output).toContain('Edges: 85');
    });

    it('includes constraints from non-auto-detected sources', () => {
        const rules: ClassifiedRule[] = [
            {
                text: 'All mutations through server actions',
                classification: 'constraint',
                source: 'CLAUDE.md',
                target: 'intent',
            },
            {
                text: 'strict mode enabled',
                classification: 'constraint',
                source: 'tsconfig',
                target: 'intent',
            },
        ];
        const output = generateSmartOverview(
            'my-app', makeAnalysis(), makeScanResult(), rules,
        );
        expect(output).toContain('## Key Constraints');
        expect(output).toContain('All mutations through server actions');
        expect(output).not.toContain('strict mode enabled');
    });

    it('includes auto-generated footer', () => {
        const output = generateSmartOverview('my-app', makeAnalysis(), makeScanResult());
        expect(output).toContain('Auto-generated by Symbiote');
    });
});
