import type { ProjectAnalysis } from './parsers/types.js';
import type { ClassifiedRule } from './parsers/types.js';
import type { ScanResult } from '../core/scanner.js';

const AUTO_DETECTED_SOURCES = new Set(['package.json', 'tsconfig', 'eslint', 'prettier']);

export function generateSmartOverview(
    projectName: string,
    analysis: ProjectAnalysis,
    scanResult: ScanResult,
    rules?: ClassifiedRule[],
): string {
    const lines: string[] = [];

    lines.push(`# ${projectName}`);
    lines.push('');

    if (analysis.description) {
        lines.push(analysis.description);
        lines.push('');
    }

    if (analysis.techStack.length > 0) {
        lines.push('## Tech Stack');
        lines.push('');

        const grouped = groupByCategory(analysis.techStack);
        for (const [category, entries] of grouped) {
            lines.push(`**${capitalize(category)}**`);
            for (const entry of entries) {
                const version = entry.version ? ` (${entry.version})` : '';
                lines.push(`- ${entry.name}${version}`);
            }
            lines.push('');
        }
    }

    if (analysis.architecture.length > 0) {
        lines.push('## Architecture');
        lines.push('');

        const sorted = [...analysis.architecture].sort(
            (a, b) => b.confidence - a.confidence,
        );
        for (const signal of sorted) {
            const pct = Math.round(signal.confidence * 100);
            lines.push(`- ${signal.pattern} (${pct}%)`);
        }
        lines.push('');
    }

    if (analysis.entryPoints.length > 0) {
        lines.push('## Entry Points');
        lines.push('');
        for (const ep of analysis.entryPoints) {
            lines.push(`- \`${ep}\``);
        }
        lines.push('');
    }

    const constraints = rules?.filter(
        (r) => r.classification === 'constraint' && !AUTO_DETECTED_SOURCES.has(r.source),
    );
    if (constraints && constraints.length > 0) {
        lines.push('## Key Constraints');
        lines.push('');
        for (const c of constraints) {
            lines.push(`- ${c.text}`);
        }
        lines.push('');
    }

    const decisions = rules?.filter(
        (r) => r.classification === 'decision' && !AUTO_DETECTED_SOURCES.has(r.source),
    );
    if (decisions && decisions.length > 0) {
        lines.push('## Key Decisions');
        lines.push('');
        for (const d of decisions) {
            lines.push(`- ${d.text}`);
        }
        lines.push('');
    }

    lines.push('## Graph Stats');
    lines.push('');
    lines.push(`- Files scanned: ${scanResult.filesScanned}`);
    lines.push(`- Nodes: ${scanResult.nodesCreated}`);
    lines.push(`- Edges: ${scanResult.edgesCreated}`);
    if (scanResult.errors.length > 0) {
        lines.push(`- Errors: ${scanResult.errors.length}`);
    }
    lines.push('');

    lines.push('---');
    lines.push('*Auto-generated by Synapse*');
    lines.push('');

    return lines.join('\n');
}

function groupByCategory(
    stack: ProjectAnalysis['techStack'],
): [string, ProjectAnalysis['techStack']][] {
    const map = new Map<string, ProjectAnalysis['techStack']>();
    for (const entry of stack) {
        const list = map.get(entry.category) ?? [];
        list.push(entry);
        map.set(entry.category, list);
    }
    return [...map.entries()];
}

function capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
